unitDef = {
  unitname            = [[jumpsumo]],
  name                = [[Jugglenaut]],
  description         = [[Heavy Riot Jumper]],
  acceleration        = 0.1,
  autoheal            = 20,
  activateWhenBuilt   = true,
  brakeRate           = 0.3,
  buildCostMetal      = 1620,
  builder             = false,
  buildPic            = [[jumpsumo.png]],
  canGuard            = true,
  canMove             = true,
  canPatrol           = true,
  category            = [[LAND]],
  collisionVolumeOffsets  = [[0 0 0]],
  collisionVolumeScales   = [[64 64 64]],
  collisionVolumeType     = [[ellipsoid]],
  corpse              = [[DEAD]],

  customParams        = {
    canjump            = 1,
    jump_range         = 470,
    jump_height        = 200,
    jump_speed         = 8.4,
    jump_delay         = 45,
    jump_reload        = 10,
    jump_from_midair   = 0,
    jump_rotate_midair = 0,
    aimposoffset   = [[0 6 0]],
    midposoffset   = [[0 6 0]],
    modelradius    = [[32]],
  },

  explodeAs           = [[BIG_UNIT]],
  footprintX          = 4,
  footprintZ          = 4,
  iconType            = [[t3jumpjetriot]],
  idleAutoHeal        = 5,
  idleTime            = 1800,
  leaveTracks         = true,
  losEmitHeight       = 60,
  maxDamage           = 12500,
  maxSlope            = 36,
  maxVelocity         = 1.1,
  maxWaterDepth       = 22,
  minCloakDistance    = 75,
  movementClass       = [[KBOT4]],
  noAutoFire          = false,
  noChaseCategory     = [[TERRAFORM FIXEDWING SATELLITE SUB]],
  objectName          = [[m-9.s3o]],
  onoffable           = true,
  script              = [[jumpsumo.lua]],
  selfDestructAs      = [[BIG_UNIT]],

  sfxtypes            = {

    explosiongenerators = {
      [[custom:sumosmoke]],
      [[custom:BEAMWEAPON_MUZZLE_ORANGE]],
    },

  },
  sightDistance       = 480,
  trackOffset         = 0,
  trackStrength       = 8,
  trackStretch        = 1,
  trackType           = [[crossFoot]],
  trackWidth          = 66,
  turnRate            = 500,
  upright             = false,
  workerTime          = 0,

  weapons             = {

    {
      def                = [[FAKELASER]],
      mainDir            = [[0 0 1]],
      maxAngleDif        = 30,
    }, --TTODO : See we can add gravity weapons without sacrificing damage to allow switching between the big plasma cannon and the plasma stream.
    {
      def                = [[GRAVITY_NEG]],
      badTargetCategory  = [[]],
      onlyTargetCategory = [[LAND SINK TURRET SHIP SWIM FLOAT HOVER GUNSHIP FIXEDWING]],
      mainDir            = [[-1 0 0]],
      maxAngleDif        = 222,
    },
    {
      def                = [[GRAVITY_NEG]],
      badTargetCategory  = [[]],
      onlyTargetCategory = [[LAND SINK TURRET SHIP SWIM FLOAT HOVER GUNSHIP FIXEDWING]],
      mainDir            = [[1 0 0]],
      maxAngleDif        = 222,
    },
    {
      def                = [[GRAVITY_POS]],
      badTargetCategory  = [[]],
      onlyTargetCategory = [[LAND SINK TURRET SHIP SWIM FLOAT HOVER GUNSHIP FIXEDWING]],
      mainDir            = [[-1 0 0]],
      maxAngleDif        = 222,
    },
    {
      def                = [[GRAVITY_POS]],
      badTargetCategory  = [[]],
      onlyTargetCategory = [[LAND SINK TURRET SHIP SWIM FLOAT HOVER GUNSHIP FIXEDWING]],
      mainDir            = [[1 0 0]],
      maxAngleDif        = 222,
    },
    {
      def                = [[LANDING]],
      badTargetCategory  = [[FIXEDWING GUNSHIP]],
      onlyTargetCategory = [[LAND SINK TURRET SHIP SWIM FLOAT HOVER GUNSHIP FIXEDWING]],
    },
  },


  weaponDefs          = {

    FAKELASER     = {
      name                    = [[Fake Laser]],
      areaOfEffect            = 12,
      beamTime                = 0.1,
      coreThickness           = 0.5,
      craterBoost             = 0,
      craterMult              = 0,

      damage                  = {
        default = 0,
        subs    = 0,
      },

      duration                = 0.11,
      edgeEffectiveness       = 0.99,
      explosionGenerator      = [[custom:flash1green]],
      fireStarter             = 70,
      impactOnly              = true,
      impulseBoost            = 0,
      impulseFactor           = 0.4,
      interceptedByShieldType = 1,
      largeBeamLaser          = true,
      laserFlareSize          = 5.53,
      minIntensity            = 1,
      noSelfDamage            = true,
      proximityPriority       = 10,
      range                   = 285,
      reloadtime              = 0.11,
      rgbColor                = [[0 1 0]],
      soundStart              = [[weapon/laser/laser_burn5]],
      soundTrigger            = true,
      texture1                = [[largelaser]],
      texture2                = [[flare]],
      texture3                = [[flare]],
      texture4                = [[smallflare]],
      thickness               = 5.53,
      tolerance               = 10000,
      turret                  = false,
      weaponType              = [[BeamLaser]],
      weaponVelocity          = 900,
    },

    GRAVITY_NEG = { --Actually heavy and slow-firing plasma weapon.
	  name                    = [[Charged energy Weapon]],
      areaOfEffect            = 64,
      cegTag                  = [[beamweapon_muzzle_blue]],
      coreThickness           = 1.3,
      craterBoost             = 0,
      craterMult              = 0,

	  customParams        	  = {
		light_camera_height = 1600,
		light_color = [[2.4 0.7 0.7]],
		light_radius = 300,
	  },
	  
      damage                  = {
        default = 600.1,
        subs    = 600.1,
      },

      edgeeffectiveness       = 0.33,
      duration                = 0.4,
      explosionGenerator      = [[custom:beamerray]],
      fireStarter             = 100,
      heightMod               = 1,
      impulseBoost            = 0,
      impulseFactor           = 0.6,
      interceptedByShieldType = 1,
      noSelfDamage            = true,
      range                   = 310,
      reloadtime              = 2.5,
      rgbColor                = [[1 0.4 0.05]],
      soundHit                = [[weapon/laser/heavy_disrupter_hit]],
	  soundStartVolume        = 1.75,
      soundStart              = [[weapon/cannon/plasma_fire]],
      soundTrigger            = true,
	  soundStartVolume        = 1.2,
      texture1                = [[energywave]],
      texture2                = [[null]],
      texture3                = [[null]],
      thickness               = 14.5,
      tolerance               = 10000,
      turret                  = true,
      weaponType              = [[LaserCannon]],
      weaponVelocity          = 190,
	  
    },


    GRAVITY_POS = { --Actually light and fast-firing plasma weapon
	  name                    = [[Direct Energy Weapon]],
      areaOfEffect            = 32,
      cegTag                  = [[beamweapon_muzzle_blue]],
      coreThickness           = 0.5,
      craterBoost             = 0,
      craterMult              = 0,

	  customParams        	  = {
		light_camera_height = 1600,
		light_color = [[0.7 0.7 2.3]],
		light_radius = 160,
	  },
	  
      damage                  = {
        default = 42.1,
        subs    = 4.2,
      },

      edgeeffectiveness       = 0.2,
      duration                = 0.3,
      explosionGenerator      = [[custom:beamerray]],
      fireStarter             = 50,
      heightMod               = 1,
      impulseBoost            = 0,
      impulseFactor           = 0.4,
      interceptedByShieldType = 1,
      noSelfDamage            = true,
      range                   = 300,
      reloadtime              = 0.35,
      rgbColor                = [[0 0.3 1]],
      soundHit                = [[weapon/laser/small_laser_fire2]],
      soundStart              = [[weapon/laser/small_laser_fire3]],
      soundTrigger            = true,
      texture1                = [[energywave]],
      texture2                = [[null]],
      texture3                = [[null]],
      thickness               = 6,
      tolerance               = 10000,
      turret                  = true,
      weaponType              = [[LaserCannon]],
      weaponVelocity          = 390,
	  
    },

    HEATRAY = {
      name                    = [[Heat Ray]],
      accuracy                = 512,
      areaOfEffect            = 20,
      coreThickness           = 0.5,
      craterBoost             = 0,
      craterMult              = 0,

      damage                  = {
        default = 50,
        subs    = 2.5,
      },

      duration                = 0.3,
      dynDamageExp            = 1,
      dynDamageInverted       = false,
      explosionGenerator      = [[custom:HEATRAY_HIT]],
      fallOffRate             = 1,
      fireStarter             = 90,
      heightMod               = 1,
      impactOnly              = true,
      impulseBoost            = 0,
      impulseFactor           = 0.4,
      interceptedByShieldType = 1,
      noSelfDamage            = true,
      proximityPriority       = 10,
      range                   = 285,
      reloadtime              = 0.1,
      rgbColor                = [[1 0.1 0]],
      rgbColor2               = [[1 1 0.25]],
      soundStart              = [[weapon/heatray_fire]],
      thickness               = 3,
      tolerance               = 5000,
      turret                  = true,
      weaponType              = [[LaserCannon]],
      weaponVelocity          = 500,
    },

    PARTICLEBEAM = {
      name                    = [[Auto Particle Beam]],
      beamDecay               = 0.85,
      beamTime                = 1/30,
      beamttl                 = 45,
      coreThickness           = 0.5,
      craterBoost             = 0,
      craterMult              = 0,

      damage                  = {
        default = 60,
        subs    = 3,
      },

      explosionGenerator      = [[custom:flash1red]],
      fireStarter             = 100,
      impactOnly              = true,
      impulseFactor           = 0,
      interceptedByShieldType = 1,
      laserFlareSize          = 7.5,
      minIntensity            = 1,
      range                   = 285,
      reloadtime              = 0.5,
      rgbColor                = [[1 0 0]],
      soundStart              = [[weapon/laser/mini_laser]],
      soundStartVolume        = 6,
      thickness               = 5,
      tolerance               = 8192,
      turret                  = true,
      weaponType              = [[BeamLaser]],
    },

	LANDING    = {
      name                    = [[LANDING]],
      areaOfEffect            = 395,
      craterBoost             = 0,
      craterMult              = 0,

      damage                  = {
        default = 640.1,
        planes  = 640.1,
        subs    = 6.4,
      },

      customParams           = {
        light_radius = 0,
        lups_explodespeed = 1,
        lups_explodelife = 0.6,
        timeslow_damagefactor = 1,
		timeslow_overslow_frames = 2*30,
      },

      edgeeffectiveness       = 0.05,
      explosionGenerator      = [[custom:FLASH64]],
      explosionSpeed          = 13,
      impulseBoost            = 1,
      impulseFactor           = 4,
      interceptedByShieldType = 1,
      myGravity               = 10,
      noSelfDamage            = true,
      range                   = 285,
      reloadtime              = 1,
      soundHitVolume          = 1,
      turret                  = true,
      weaponType              = [[Cannon]],
      weaponVelocity          = 230,
    },

  },


  featureDefs         = {

    DEAD = {
      blocking         = true,
      featureDead      = [[HEAP]],
      footprintX       = 3,
      footprintZ       = 3,
      object           = [[m-9_wreck.s3o]],
    },


    HEAP = {
      blocking         = false,
      footprintX       = 3,
      footprintZ       = 3,
      object           = [[debris3x3a.s3o]],
    },

  },

}

return lowerkeys({ jumpsumo = unitDef })
